#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

COMMAND=(
  "$REPO_ROOT/espresso"
  suite
  --prompts "${ESPRESSO_AUTORESEARCH_PROMPTS_FILE:-$REPO_ROOT/scripts/benchmark-prompts.txt}"
)

[[ -n "${ESPRESSO_AUTORESEARCH_MODEL:-}" ]] && COMMAND+=(--model "$ESPRESSO_AUTORESEARCH_MODEL")
[[ -n "${ESPRESSO_AUTORESEARCH_WEIGHTS_DIR:-}" ]] && COMMAND+=(--weights "$ESPRESSO_AUTORESEARCH_WEIGHTS_DIR")
[[ -n "${ESPRESSO_AUTORESEARCH_TOKENIZER_DIR:-}" ]] && COMMAND+=(--tokenizer "$ESPRESSO_AUTORESEARCH_TOKENIZER_DIR")
[[ -n "${ESPRESSO_AUTORESEARCH_COREML_MODEL:-}" ]] && COMMAND+=(--coreml-model "$ESPRESSO_AUTORESEARCH_COREML_MODEL")
[[ -n "${ESPRESSO_AUTORESEARCH_COREML_SEQ_LEN:-}" ]] && COMMAND+=(--coreml-seq-len "$ESPRESSO_AUTORESEARCH_COREML_SEQ_LEN")
[[ -n "${ESPRESSO_AUTORESEARCH_COREML_COMPUTE_UNITS:-}" ]] && COMMAND+=(--coreml-compute-units "$ESPRESSO_AUTORESEARCH_COREML_COMPUTE_UNITS")
[[ -n "${ESPRESSO_AUTORESEARCH_RESULTS_TSV:-}" ]] && COMMAND+=(--results-tsv "$ESPRESSO_AUTORESEARCH_RESULTS_TSV")
[[ -n "${ESPRESSO_AUTORESEARCH_MAX_TOKENS:-}" ]] && COMMAND+=(--max-tokens "$ESPRESSO_AUTORESEARCH_MAX_TOKENS")
[[ -n "${ESPRESSO_AUTORESEARCH_WARMUP:-}" ]] && COMMAND+=(--compare-warmup "$ESPRESSO_AUTORESEARCH_WARMUP")
[[ -n "${ESPRESSO_AUTORESEARCH_ITERATIONS:-}" ]] && COMMAND+=(--compare-iterations "$ESPRESSO_AUTORESEARCH_ITERATIONS")
[[ -n "${ESPRESSO_AUTORESEARCH_RUNS:-}" ]] && COMMAND+=(--runs "$ESPRESSO_AUTORESEARCH_RUNS")

exec "${COMMAND[@]}" "$@"
